name: CICD pipline

on:
  push:
    branches: [master, main]

jobs:
  deploy_code:
    name: deploy_code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: install packages
        run: npm install

      - name: deploy to aws ec2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ec2-16-16-67-150.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/expressjs_test_app_for_deployment"
          rm: false
          overwrite: true
